<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuBuilderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin_menus = array(
            array(
                "id" => 2,
                "name" => "footer_menu_one",
                "created_at" => "2024-07-15 20:53:28",
                "updated_at" => "2024-07-15 20:53:28",
            ),
            array(
                "id" => 3,
                "name" => "footer_menu_two",
                "created_at" => "2024-07-15 20:53:39",
                "updated_at" => "2024-07-15 20:53:39",
            ),
            array(
                "id" => 4,
                "name" => "footer_menu_three",
                "created_at" => "2024-07-15 20:53:47",
                "updated_at" => "2024-07-15 20:53:47",
            ),
            array(
                "id" => 5,
                "name" => "main_menu",
                "created_at" => "2024-07-16 11:16:15",
                "updated_at" => "2024-07-16 11:16:15",
            ),
        );

        $admin_menu_items = array(
            array(
                "id" => 1,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2024-07-15 21:10:56",
                "updated_at" => "2024-07-15 21:11:11",
            ),
            array(
                "id" => 2,
                "label" => "About Us",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2024-07-15 21:11:12",
                "updated_at" => "2024-07-15 21:11:12",
            ),
            array(
                "id" => 3,
                "label" => "Contact Us",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2024-07-15 21:11:22",
                "updated_at" => "2024-07-15 21:11:22",
            ),
            array(
                "id" => 4,
                "label" => "Our Service",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2024-07-15 21:11:48",
                "updated_at" => "2024-07-15 21:11:48",
            ),
            array(
                "id" => 5,
                "label" => "More About Us",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2024-07-15 21:12:03",
                "updated_at" => "2024-07-15 21:12:03",
            ),
            array(
                "id" => 6,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 0,
                "created_at" => "2024-07-16 11:16:36",
                "updated_at" => "2024-07-16 11:16:50",
            ),
            array(
                "id" => 7,
                "label" => "About Us",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 0,
                "created_at" => "2024-07-16 11:16:50",
                "updated_at" => "2024-07-16 11:17:02",
            ),
            array(
                "id" => 8,
                "label" => "Chefs",
                "link" => "/chefs",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 0,
                "created_at" => "2024-07-16 11:17:02",
                "updated_at" => "2024-07-16 11:17:02",
            ),
            array(
                "id" => 9,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 0,
                "created_at" => "2024-07-16 11:17:17",
                "updated_at" => "2024-07-16 11:17:17",
            ),
            array(
                "id" => 10,
                "label" => "Contact Us",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 0,
                "created_at" => "2024-07-16 11:17:32",
                "updated_at" => "2024-07-16 11:17:32",
            ),
            array(
                "id" => 11,
                "label" => "Pages",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 5,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 0,
                "created_at" => "2024-07-16 11:17:48",
                "updated_at" => "2024-07-16 11:17:48",
            ),
            array(
                "id" => 12,
                "label" => "Cart View",
                "link" => "/cart",
                "parent_id" => 11,
                "sort" => 6,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 1,
                "created_at" => "2024-07-16 11:18:22",
                "updated_at" => "2024-07-16 11:20:01",
            ),
            array(
                "id" => 13,
                "label" => "Testimonials",
                "link" => "/testimonials",
                "parent_id" => 11,
                "sort" => 7,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 1,
                "created_at" => "2024-07-16 11:18:40",
                "updated_at" => "2024-07-16 11:20:06",
            ),
            array(
                "id" => 14,
                "label" => "Sign In",
                "link" => "/login",
                "parent_id" => 11,
                "sort" => 8,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 1,
                "created_at" => "2024-07-16 11:19:08",
                "updated_at" => "2024-07-16 11:20:09",
            ),
            array(
                "id" => 15,
                "label" => "Sign Up",
                "link" => "/register",
                "parent_id" => 11,
                "sort" => 9,
                "class" => NULL,
                "menu_id" => 5,
                "depth" => 1,
                "created_at" => "2024-07-16 11:19:38",
                "updated_at" => "2024-07-16 11:20:11",
            ),
            array(
                "id" => 16,
                "label" => "Privacy Policy",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2024-07-16 15:05:59",
                "updated_at" => "2024-07-16 15:06:26",
            ),
            array(
                "id" => 17,
                "label" => "Terms And Condiitons",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2024-07-16 15:06:26",
                "updated_at" => "2024-07-16 15:06:39",
            ),
            array(
                "id" => 18,
                "label" => "Refund Policy",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2024-07-16 15:06:39",
                "updated_at" => "2024-07-16 15:06:53",
            ),
            array(
                "id" => 19,
                "label" => "FAQ",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2024-07-16 15:06:53",
                "updated_at" => "2024-07-16 15:07:04",
            ),
            array(
                "id" => 20,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2024-07-16 15:07:04",
                "updated_at" => "2024-07-16 15:07:07",
            ),
            array(
                "id" => 21,
                "label" => "FAQs",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2024-07-16 15:07:31",
                "updated_at" => "2024-07-16 15:07:41",
            ),
            array(
                "id" => 22,
                "label" => "Payment",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2024-07-16 15:07:41",
                "updated_at" => "2024-07-16 15:07:41",
            ),
            array(
                "id" => 23,
                "label" => "Settings",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2024-07-16 15:07:50",
                "updated_at" => "2024-07-16 15:07:50",
            ),
            array(
                "id" => 24,
                "label" => "Privacy Policy",
                "link" => "javascript:;",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2024-07-16 15:08:08",
                "updated_at" => "2024-07-16 15:08:08",
            ),
        );

        DB::table('admin_menus')->insert($admin_menus);
        DB::table('admin_menu_items')->insert($admin_menu_items);
    }
}
